### ISSUE TITLE
Stuck at "Setting up Twitter...."

### ISSUE THREAD

**Issue by 9gga** [mastashake08/discord-twitter-bot#8]
I've tried to run node main.js as root but i get stuck at Setting up Twitter.... without any error code.

**Comment by mastashake08** [comment]
Can you attach some screenshots? Are you sure you have all your .env creds
set up?
*Jyrone Parker*
*Technical Consultant, *Technopreneur

*Never Let Limited Minds Limit Your Success*
*https://www.jyroneparker.com <http://www.jyroneparker.com> |
https://youtube.com/c/jyroneparker <https://youtube.com/c/jyroneparker>*
Twitter: https://twitter.com/jyroneparker
Instagram: https://instagram.com/mastashake08
